{
  'env': { 'browser': true, 'node': true, 'es2022': true },
  'extends':
    [
      'eslint:recommended',
      'prettier',
      'plugin:react/recommended',
      'plugin:react-hooks/recommended',
      'plugin:import/recommended',
      'plugin:import/typescript',
      'plugin:jsx-a11y/recommended',
      'plugin:tailwindcss/recommended'
    ],
  'plugins': ['prettier', 'react', 'react-hooks', '@typescript-eslint', 'tailwindcss', 'import', 'jsx-a11y'],
  'parser': '@typescript-eslint/parser',
  'parserOptions': { 'ecmaVersion': 'latest', 'sourceType': 'module', 'ecmaFeatures': { 'jsx': true } },
  'settings': { 'import/resolver': { 'typescript': {} }, 'react': { 'version': 'detect' } },
  'rules':
    {
      'arrow-body-style': 'off',
      'eqeqeq': 1,
      'object-shorthand': 'warn',
      'prefer-arrow-callback': 'warn',
      'prettier/prettier': 'warn',
      'react/react-in-jsx-scope': 'off',
      'react/display-name': 'off',
      'react/prop-types': "off",
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': [1, { 'varsIgnorePattern': '^_', 'argsIgnorePattern': '^_' }],
      '@typescript-eslint/ban-ts-comment': 'off',
    },
}
